### ISSUE TITLE
Liveness/readiness probes won't work when the mTLS server is enabled

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco-exporter#50]
**Describe the bug**

Liveness/readiness probes won't work when the mTLS server is enabled, as noticed by @jasiam

**How to reproduce it**

Since the current deployment manifest nor the helm chart are providing this feature, a custom deployment is needed to reproduce the problem.

Basically, falco-exporter needs to be deployed on a K8s cluster with certs and `--server-*` flags.

A convenient way to do that for debugging purpose is to create a custom docker image that includes cert materials, then deploy it using the following manifest:
```yaml
---
# Source: falco-exporter/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco-exporter
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: falco-exporter
      app.kubernetes.io/instance: falco-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: falco-exporter
        app.kubernetes.io/instance: falco-exporter
    spec:
      serviceAccountName: falco-exporter
      securityContext:
        {}
      containers:
        - name: falco-exporter
          securityContext:
            {}
          image: "falco-exporter-test-cert:latest"
          imagePullPolicy: IfNotPresent
          args:
            - /usr/bin/falco-exporter
            - --client-socket=unix:///var/run/falco/falco.sock
            - --timeout=2m
            - --listen-address=0.0.0.0:9376
            - --server-ca=/ca.crt 
            - --server-cert=/server.crt
            - --server-key=/server.key
          ports:
            - name: metrics
              containerPort: 9376
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9376
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9376
          resources:
            {}
          volumeMounts:
            - mountPath: /var/run/falco
              name: falco-socket-dir
              readOnly: true
      volumes:
        - name: falco-socket-dir
          hostPath:
            path: /var/run/falco
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
```

**Expected behaviour**

Probes also work when mTLS server is enabled.

**Screenshots**

**Additional context**
